<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

if ($block->checkNitroHeaderCacheIsMiss()):
    ?>
    <script>
        NPTelemetryMetadata = {
            "pageType": "<?= /* @noEscape */ $block->getPageType(); ?>",
            "missReason": "<?= /* @noEscape */ $block->getPageHeaderMissReason(); ?>",
            "isEligibleForOptimization": <?= /* @noEscape */ $block->isEligibleForOptimization(); ?>
        };

    </script>
    <?php
    if ($block->fetchTelemetryJs()): ?>
        <script  type="text/javascript" defer>
                <?= /* @noEscape */ $block->fetchTelemetryJs();?>
        </script>
    <?php
    endif; ?>
<?php
endif; ?>
