<?php
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

if ($block->checkNitroHeaderCacheIsMiss()):
    ?>
    <script>
        NPTelemetryMetadata = {
            PAGE_TYPE: "<?= $block->getPageType(); ?>",
            MISS_REASON: "<?= $block->getPageHeaderMissReason(); ?>"
        };

    </script>
    <?php
    if ($block->fetchTelemetryJs()): ?>
        <script  type="text/javascript" defer>
                <?= $block->fetchTelemetryJs();?>
        </script>
    <?php
    endif; ?>
<?php
endif; ?>
