<?php

namespace NitroPack\NitroPack;

use Composer\Installer\InstallerInterface;
use Composer\Installer\LibraryInstaller;

class NitroPackInstaller extends LibraryInstaller implements InstallerInterface
{

    private $objectManager;

    public function __construct(
        \Composer\IO\IOInterface $io,
        \Composer\Composer $composer,
        $type = 'library',
        \Composer\Util\Filesystem $filesystem = null,
        \Composer\Installer\BinaryInstaller $binaryInstaller = null,
        \Magento\Framework\ObjectManagerInterface $objectManager
    ) {
        $this->objectManager = $objectManager;
        parent::__construct($io, $composer, $type, $filesystem, $binaryInstaller);
    }

    public function uninstall(
        \Composer\Repository\InstalledRepositoryInterface $repo,
        \Composer\Package\PackageInterface $package
    ) {
        var_dump(get_class($this->objectManager));
        exit();
        return parent::uninstall($repo, $package); // TODO: Change the autogenerated stub
    }
}
