<?php

namespace NitroPack\NitroPack;

use Composer\Installer\InstallerInterface;
use Composer\Installer\LibraryInstaller;
use Composer\Package\PackageInterface;
use Composer\Repository\InstalledRepositoryInterface;

class TemplateInstaller extends LibraryInstaller implements InstallerInterface
{

    public function uninstall(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        die("SHAZA");
        return parent::uninstall($repo, $package); // TODO: Change the autogenerated stub
    }

}
