<?php

$nitroPackConfigHelper = $this->helper('NitroPack\NitroPack\Helper\NitroPackConfigHelper');

$fastlyHelper = $this->helper('NitroPack\NitroPack\Helper\FastlyHelper');
$settings = $block->getSettings();
$enabledMagentoCaches = $nitroPackConfigHelper->getDisabledCaches();

?>
<div class="h-auto max-w-full card-radius pad-24 bg-white border border-gray-200 rounded-md shadow items-center" id="setting-widget">

    <div class="flex flex-row items-center justify-between border-b border-gray-200" >
        <h6 class="text-base font-bold text-gray-900 optimize-page-head mb-8">General settings</h6>
    </div>
    <!---- Extension Status ---->
    <div x-data="{isCheckedEnabled:<?= /* @noEscape */ (isset($settings->enabled) && $settings->enabled ? "true" : "false" );?> , showEnabledModal :false}" @keydown.escape="showEnabledModal = false" id="extension-status-widget">
    <div class="flex flex-row items-center justify-between mt-6 mb-6" >
        <div class="flex-row">
        <h6 class="text-base font-bold text-gray-900 optimize-page-head">Extension status</h6>
        <p class="text-xl text-gray-900 text-lite-gray pt-2 general-font-size font-inter">Master ON/OFF switch for the extension.</p>
        </div>
        <label class="inline-flex items-center me-5 cursor-pointer">
            <input id="status" x-model="isCheckedEnabled" type="checkbox"
                   name="enabled" <?php if (!empty($enabledMagentoCaches) || (!$nitroPackConfigHelper->getFullPageCacheValue() && (!$fastlyHelper->isFastlyAndNitroPackEnabled() || !$fastlyHelper->isFastlyAndNitroDisable()  ))) {
                echo "disabled";
            } ?>  x-on:change=" isCheckedEnabled ? window.enableExtension(true) :  showEnabledModal=true"
                   class="sr-only peer">
            <div
                class="toggle-height toggle-width relative bg-lite-purple-200 <?php if (!empty($enabledMagentoCaches) || (!$nitroPackConfigHelper->getFullPageCacheValue() && (!$fastlyHelper->isFastlyAndNitroPackEnabled() || !$fastlyHelper->isFastlyAndNitroDisable()  ))) {
                    echo "disabled";
                } ?> peer-focus:outline-none dark:peer-focus:ring-purple rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:transition-all dark:border-gray-600 peer-checked:bg-purple"></div>
        </label>
    </div>
        <?= /* @noEscape */ $this->getChildHtml('EnabledConfirmPopup'); ?>

    </div>
    <div class="flex flex-row items-center border-b border-gray-200"></div>

    <!---- Cache Warmup ---->
    <div x-data="{isCheckedCacheWarmup:<?= /* @noEscape */ (isset($settings->cacheWarmup) && $settings->cacheWarmup ? "true" : "false" );?> , isShowCacheWarmup:false }" @keydown.escape="showCacheWarmupModal = false" id="cache-warmup-widget">
    <div class="flex flex-row items-center justify-between mt-6 mb-6" >
        <div class="flex-row">
        <h6 class="text-base font-bold text-gray-900 optimize-page-head ">Cache warmup <span class="badge-warning p-2 text-xl font-normal">Recommended</span></h6>
        <p class="text-xl text-gray-900 text-lite-gray pt-2 general-font-size font-inter">Automatically pre-caches your website's page content. <a href="https://support.nitropack.io/en/articles/8390320-cache-warmup" target="_blank" rel="noreferrer noopener" class="text-blue">Learn more</a></p>
        </div>
        <label class="items-center me-5 cursor-pointer">
            <input id="cache_warmup" type="checkbox" x-model="isCheckedCacheWarmup" x-on:change=" if(isCheckedCacheWarmup){ isShowCacheWarmup=true; window.loadNumberOfPage();window.setCacheWarmup(true); }else{  isShowCacheWarmup=false;window.setCacheWarmup(false);}"  name="cacheWarmup" <?= /* @noEscape */ ($settings->cacheWarmup ? 'checked' : '') ?>
                   class="sr-only peer">
            <div
                class="toggle-height toggle-width relative bg-lite-purple-200 peer-focus:outline-none dark:peer-focus:ring-purple rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:transition-all dark:border-gray-600 peer-checked:bg-purple"></div>
        </label>

    </div>

<!--    <div class="flex flex-row items-center pb-5">-->
<!--        <p class="text-xl text-gray-900 text-lite-gray pt-2 general-font-size font-inter">Automatically pre-caches your website's page content. <a href="https://support.nitropack.io/en/articles/8390320-cache-warmup" target="_blank" rel="noreferrer noopener" class="text-blue">Learn more</a></p>-->
<!--    </div>-->
    <div class="flex flex-row items-center msg-container mt-2" x-show="isShowCacheWarmup" id="loading-warmup-status"  style="display: none;">
        <img src="<?= /* @noEscape */ $block->getImage('loading.svg'); ?>" alt="loading" id="npCacheWarmupLoading" class="icon-left" >
        <span class="warmup-status-message ml-2" >Estimating Optimization Usage</span>
    </div>
    <div class="flex flex-row items-center border-b border-gray-200"></div>
    </div>
    <!---- Enhanced Caching With Caching Variation ---->
    <div class="flex flex-row items-center justify-between mt-6 mb-6" id="caching-variation-widget">
        <div class="flex-row">
        <h6 class="text-base font-bold text-gray-900 optimize-page-head pt-2">Enhanced caching with caching
            variation</h6>
        <p class="text-xl text-gray-900 text-lite-gray pt-2 general-font-size font-inter">Cache different versions of a page based on customer group,<br/>selected store, currency, language, and customer logged in or not.</p>
    </div>
        <label class="inline-flex items-center me-5 cursor-pointer" >
            <input id="cache_to_customer_login" type="checkbox"
                   name="cache_to_login_customer" <?= /* @noEscape */ (isset($settings->cache_to_login_customer) && $settings->cache_to_login_customer ? 'checked' : '') ?>
                   class="sr-only peer">
            <div
                class="toggle-height toggle-width relative bg-lite-purple-200 peer-focus:outline-none dark:peer-focus:ring-purple rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:transition-all dark:border-gray-600 peer-checked:bg-purple"></div>
        </label>
    </div>
    <div class="flex flex-row items-center border-b border-gray-200">
    </div>
    <!---- Test Mode ---->
    <div x-data="{ showTestModeModal: false,isCheckedTestMode:<?= /* @noEscape */ (isset($settings->safeMode) && $settings->safeMode ? "true" : "false" );?> ,showTestModeDisableModal:false }" @keydown.escape="showTestModeModal = false,showTestModeDisableModal=false" id="test-mode-widget">
    <div class="flex flex-row items-center justify-between mt-6 mb-6" >
        <div class="flex-row">
        <h6 class="text-base font-bold text-gray-900 optimize-page-head">Test Mode</h6>
        <p class="text-xl text-gray-900 text-lite-gray  pt-2 general-font-size font-inter">Test NitroPack's features without affecting your visitors<br>
            experience. <a href="https://support.nitropack.io/hc/en-us/articles/360060910574-Safe-Mode" target="_blank"
                          rel="noreferrer noopener" class="text-blue">Learn more</a></p>
        </div>
        <label class="inline-flex items-center me-5 cursor-pointer">
            <input id="safe_mode"  x-model="isCheckedTestMode" x-on:change="window.removeDisabledSafeModeBtn, isCheckedTestMode ? showTestModeModal=true  : showTestModeDisableModal=true, window.setTestMode(isCheckedTestMode)" type="checkbox"
                   name="safeMode" <?= /* @noEscape */ (isset($settings->safeMode) && $settings->safeMode ? 'checked' : '') ?>
                   class="sr-only peer">
            <div
                class="toggle-height toggle-width relative bg-lite-purple-200 peer-focus:outline-none dark:peer-focus:ring-purple rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:transition-all dark:border-gray-600 peer-checked:bg-purple"></div>
        </label>

        <?= /* @noEscape */ $this->getChildHtml('TestModePopup'); ?>
        <?= /* @noEscape */ $this->getChildHtml('TestModeDisablePurgePopup'); ?>

    </div>
    <div class="flex flex-row items-center">

    </div>
        <div class="flex flex-row items-center border-b border-gray-200"></div>
    </div>
    <!---- Gzip ---->
    <?php
    if (isset($_SERVER['HTTP_ACCEPT_ENCODING']) && strpos($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') !== false) {
        $getHeader = get_headers($block->getStoreUrls(), true);
       if (isset($getHeader['Content-Encoding']) && $getHeader['Content-Encoding'] != 'gzip') { ?>
            <div class="flex flex-row items-center justify-between mt-6 mb-6" id="gzip-widget">
                <h6 class="text-base font-bold text-gray-900 optimize-page-head">GZIP Compression</h6>
                <label class="inline-flex items-center me-5 cursor-pointer">
                    <input id="gzip_mode" type="checkbox"
                           name="gzip" <?= /* @noEscape */ (isset($settings->gzip) && $settings->gzip ? 'checked' : '') ?>
                           class="sr-only peer">
                    <div
                        class="toggle-height toggle-width relative bg-lite-purple-200 peer-focus:outline-none dark:peer-focus:ring-purple rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[4px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:transition-all dark:border-gray-600 peer-checked:bg-purple"></div>
                </label>

            </div>
        <div class="flex flex-row items-center border-b border-gray-200">
           <p class="text-xl text-gray-900 text-lite-gray pt-2 general-font-size font-inter">
            Compressing the structure of your HTML, ensures faster page rendering and an optimized browsing <br>experience for your users.</p>
            </div>
        <?php  }} ?>
    <div class="flex flex-row items-center border-gray-200 mt-6 mb-6">
        <p class="text-l font-inter text-gray-500 text-lite-gray general-font-size font-inter">Adjust optimization settings at your NitroPack app</p>
        <button onclick="window.open('https://app.nitropack.io/dashboard<?= (isset($settings->siteId)) && $settings->siteId ? '?update_session_website_id='. $settings->siteId : '' ?>', '_blank');" type="button"
                class="ml-auto text-white font-inter font-medium py-2 px-4 border border-purple-500 rounded bg-purple hover:bg-purple-200 hover:text-white goBtn"
                style="height:36px; padding: 4px 12px 4px 12px;border-radius: 4px; width: 126px;">
            Go to app
        </button>
    </div>
    <div class="flex flex-row items-center border-gray-200 pt-6 border-t" x-data="{ 'showDisconnectModal': false,disconnectClicked:false }"
         @keydown.escape="showDisconnectModal = false">
        <a href="javascript:void(0);" @click="showDisconnectModal = true, toggleOverflow(true), window.isTestMode()" id="showDisconnectModal"
           class="mr-auto text-purple-500 text-sm hover:no-underline font-inter">Disconnect NitroPack plugin</a>
        <?= /* @noEscape */ $this->getChildHtml('DisconnectPopup'); ?>

    </div>
</div>


