<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Backend\Block\Store\Switcher */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */


$storeGroupId = (int)$this->getRequest()->getParam('group');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
if ($storeGroupId == 0) {
    // This happens when the user has selected "All store views", use the default configured store
    // @TODO the user should be notified that they're editing the settings for the default store view, not all store views

    $storeGroupId = $storeManager->getGroup()->getId();
    $currentStoreName = $storeManager->getGroup()->getName();
} else {
    $currentStoreName = $block->getCurrentStoreGroupName();
}
?>

<?php
if ($websites = $block->getWebsites()): ?>
    <div class="store-switcher store-view">
        <span class="store-switcher-label"><?= $block->escapeHtml(__('Store:')) ?></span>
        <div class="actions dropdown closable">
            <input type="hidden" name="store_switcher" id="store_switcher"
                   data-role="store-view-id" data-param="<?= $block->escapeHtmlAttr($block->getStoreVarName()) ?>"
                   value="<?= $block->escapeHtml($block->getStoreId()) ?>"
                <?php
                if (!isset($secureRenderer)) { ?>  onchange="switchScope(this);" <?php
                } ?><?= /* @noEscape */
                    $block->getUiId() ?> />
            <?php if (isset($secureRenderer)) {?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onchange',
                    'switchScope(this);',
                    '#store_switcher'
                ) ?>
            <?php } ?>
            <input type="hidden" name="store_group_switcher" id="store_group_switcher"
                   data-role="store-group-id" data-param="<?= $block->escapeHtmlAttr($block->getStoreGroupVarName()) ?>"
                   value="<?= $block->escapeHtml($block->getStoreGroupId()) ?>"
                <?php
                if (!isset($secureRenderer)) { ?> onchange="switchScope(this);" <?php
                } ?><?= /* @noEscape */
                    $block->getUiId() ?> />
            <?php if (isset($secureRenderer)) {?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onchange',
                    'switchScope(this);',
                    '#store_group_switcher'
                ) ?>
            <?php } ?>
            <input type="hidden" name="website_switcher" id="website_switcher"
                   data-role="website-id" data-param="<?= $block->escapeHtmlAttr($block->getWebsiteVarName()) ?>"
                   value="<?= $block->escapeHtml($block->getWebsiteId()) ?>"
                <?php
                if (!isset($secureRenderer)) { ?> onchange="switchScope(this);"<?php
                } ?> <?= /* @noEscape */
                    $block->getUiId() ?> />
            <?php if (isset($secureRenderer)) {?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onchange',
                    'switchScope(this);',
                    '#website_switcher'
                ) ?>
            <?php } ?>
            <button
                type="button"
                class="admin__action-dropdown"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                aria-haspopup="true"
                id="store-change-button">
                <?= $block->escapeHtml($currentStoreName) ?>
            </button>
            <ul class="dropdown-menu" data-role="stores-list">

                <?php
                foreach ($websites as $website): ?>
                    <?php
                    $showWebsite = false; ?>
                    <?php
                    foreach ($website->getGroups() as $group): ?>
                        <?php
                        $showGroup = false; ?>
                        <?php
                        foreach ($block->getStores($group) as $store): ?>

                            <?php
                            if ($showGroup == false): ?>
                                <?php
                                $showGroup = true; ?>
                                <li class="store-switcher-store <?php
                                if (!($block->isStoreGroupSwitchEnabled() &&
                                    !$block->isStoreGroupSelected($group))): ?>disabled<?php
                                endif; ?> <?php
                                if ($block->isStoreGroupSelected($group)): ?>current<?php
                                endif; ?>">
                                    <?php
                                    if ($block->isStoreGroupSwitchEnabled() &&
                                        !$block->isStoreGroupSelected($group)): ?>
                                        <a data-role="store-group-id"
                                           data-value="<?= $block->escapeHtmlAttr($group->getId()) ?>" href="#">
                                            <?= $block->escapeHtml($group->getName()) ?>
                                        </a>
                                    <?php
                                    else: ?>
                                        <span><?= $block->escapeHtml($group->getName()) ?></span>
                                    <?php
                                    endif; ?>
                                </li>
                            <?php
                            endif; ?>

                        <?php
                        endforeach; ?>
                    <?php
                    endforeach; ?>
                <?php
                endforeach; ?>
                <?php
                if ($block->getShowManageStoresLink() &&
                    $block->getAuthorization()->isAllowed('Magento_Backend::store')): ?>
                    <li class="dropdown-toolbar">
                        <a href="<?= /* @noEscape */
                        $block->getUrl('*/system_store');
                        ?>"><?= $block->escapeHtml(__('Stores Configuration')) ?></a>
                    </li>
                <?php
                endif; ?>
            </ul>
        </div>
        <?= $block->getHintHtml() ?>
    </div>
    <?php
    if (!isset($secureRenderer)) { ?>
        <script>
            require([
                'jquery',
                'Magento_Ui/js/modal/confirm'
            ], function (jQuery, confirm) {

                (function ($) {
                    var $storesList = $('[data-role=stores-list]');
                    $storesList.on('click', '[data-value]', function (event) {
                        var val = $(event.target).data('value');
                        var role = $(event.target).data('role');
                        var switcher = $('[data-role=' + role + ']');

                        event.preventDefault();

                        if (!switcher.val() || val != switcher.val()) {
                            switcher.val(val).trigger('change'); // Set the value & trigger event
                        }
                    });
                })(jQuery);

                var scopeSwitcherHandler;

                function switchScope(obj) {
                    var switcher = jQuery(obj);
                    var scopeId = switcher.val();
                    var scopeParams = '';
                    if (scopeId) {
                        scopeParams = switcher.data('param') + '/' + scopeId + '/';
                    }

                    if (obj.switchParams) {
                        scopeParams += obj.switchParams;
                    }

                    if ((typeof scopeSwitcherHandler) != 'undefined') {
                        var switcherParams = {
                            scopeId: scopeId,
                            scopeParams: scopeParams,
                            useConfirm: <?= (int)$block->getUseConfirm() ?>
                        };
                        scopeSwitcherHandler(switcherParams);
                    } else {

                        <?php if ($block->getUseConfirm()) : ?>

                        confirm({
                            content: "<?= $block->escapeJs(
                                __('Please confirm scope switching. All data that hasn\'t been saved will be lost.')
                            ) ?>",
                            actions: {
                                confirm: function () {
                                    reload();
                                },
                                cancel: function () {
                                    obj.value = '<?= $block->escapeHtml($block->getStoreId()) ?>';
                                }
                            }
                        });

                        <?php else : ?>
                        reload();
                        <?php endif; ?>
                    }

                    function reload() {
                        <?php if (!$block->isUsingIframe()) : ?>
                        var url = '<?= $block->escapeJs($block->getSwitchUrl()) ?>' + scopeParams;
                        setLocation(url);
                        <?php else : ?>
                        jQuery('#preview_selected_store').val(scopeId);
                        jQuery('#preview_form').submit();

                        jQuery('.store-switcher .dropdown-menu li a').each(function () {
                            var $this = jQuery(this);

                            if ($this.data('role') === 'store-view-id' && $this.data('value') == scopeId) {
                                jQuery('#store-change-button').html($this.text());
                            }
                        });

                        jQuery('#store-change-button').click();
                        <?php endif; ?>
                    }
                }

                window.scopeSwitcherHandler = scopeSwitcherHandler;
                window.switchScope = switchScope;

            });
        </script>
        <?php
    } ?>
    <?php
    if (isset($secureRenderer)) { ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Backend/js/store-switcher": {
                    "useConfirm": <?= /* @noEscape */ (int)$block->getUseConfirm(); ?>,
                    "isUsingIframe": <?= /* @noEscape */ (int)$block->isUsingIframe(); ?>,
                    "switchUrl": "<?= $block->escapeUrl($block->getSwitchUrl()); ?>",
                    "storeId": <?= /* @noEscape */ (int)$block->getStoreId(); ?>
                }
            }
        }
    </script>
        <?php
    } ?>
<?php
endif; ?>
