<div style="z-index: 999; background: rgb(42, 0, 122, 0.5); display: none;"
     class="fixed inset-0 z-30 flex items-center justify-center overflow-auto" x-show="showDisconnectModal">
    <div
        class="h-auto max-w-full rounded-lg pad-24 bg-white border border-gray-200 rounded-md shadow items-center popup-container">
        <!-- Modal inner -->
        <div class="flex justify-right" style="float: right; clear: both;">
            <button type="button" class="z-50 cursor-pointer"
                    @click="showDisconnectModal = false, toggleOverflow(false)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </button>
        </div>
        <div class="flex flex-row items-center justify-center">
            <div class="flex items-center justify-center">
                <img src="<?= $block->getImage("info.svg"); ?>" alt="After Processing Image" width="46"
                     class="rotate-180 img-pop-align"
                     height="46">
            </div>
        </div>
        <div id="test-mode-disabled">
            <div class="flex flex-row items-center justify-center mt-8">
                <h3 class="text-base font-bold text-gray-900 optimize-page-head modal-heading">Are you sure you want to
                    disconnect
                    NitroPack?</h3>
            </div>
            <div class="items-center justify-center mt-8">
                <p class="text-l font-inter text-gray-500 text-lite-gray popup-text text-center">
                    Disconnecting NitroPack will delete your page optimizations,<br> potentially slowing down your
                    website and worsening the user experience.
                </p>
                <p class="text-l font-inter text-gray-500 text-lite-gray popup-text mt-8 text-center">
                    Please use "Test mode" for troubleshooting potential issues without negatively impacting your site's
                    performance.
                </p>
            </div>
            <div class="flex flex-row items-center justify-center mt-10 items-center">
                <div class="flex items-center justify-center">
                    <button @click=" toggleOverflow(false)" type="button"
                            class="disconnect bg-transparent text-purple-700 font-medium font-inter border border-purple-500 rounded cancel-btn">
                        <img src="<?= $block->getImage('loading.svg'); ?>" alt="loading"  class="icon-left npDisconnectLoading" style="display: none; margin-bottom: 3px;">
                        <img src="<?=  $block->getImage('check.svg');?>" alt="loading"  class="icon-left npDisconnectSuccess" style="display: none;">
                        Disconnect Anyway
                    </button>
                </div>
                <div class="flex items-center justify-center">
                    <button type="button" @click="isCheckedTestMode = true, window.safeModeActive(), window.setTestMode(true), showDisconnectModal = false, toggleOverflow(false)"
                            class="disconnectBtn text-white font-medium font-inter border border-purple-500 rounded">Switch to Test mode
                    </button>
                </div>
            </div>
        </div>
        <div id="test-mode-enabled">
            <div class="flex flex-row items-center justify-center mt-8">
                <h3 class="text-base font-bold text-gray-900 optimize-page-head modal-heading">Are you sure you want to
                    disconnect
                    NitroPack?</h3>
            </div>
            <div class="items-center justify-center mt-8">
                <p class="text-l font-inter text-gray-500 text-lite-gray popup-text text-center">
                    Disconnecting NitroPack will immediately stop page optimizations, potentially slowing down your site and affecting user experience.
                </p>
            </div>

            <div class="flex flex-row items-center justify-center mt-10 items-center">
                <div class="flex items-center justify-center">
                    <button @click="showDisconnectModal = false, toggleOverflow(false)"  type="button"
                            class="bg-transparent text-purple-700 font-medium font-inter border border-purple-500 rounded cancel-btn">
                        Cancel
                    </button>
                </div>
                <div class="flex items-center justify-center">
                    <button type="button" @click="toggleOverflow(false)"
                            class="disconnect text-white font-medium font-inter border border-purple-500 rounded disconnectBtn">
                        <img src="<?= $block->getImage('loading.svg'); ?>" alt="loading"  class="icon-left npDisconnectLoading" style="display: none; margin-bottom: 3px;">
                        <img src="<?=  $block->getImage('check.svg');?>" alt="loading"  class="icon-left npDisconnectSuccess" style="display: none;">Disconnect
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
