<div style="z-index: 999; background: rgb(42, 0, 122, 0.5); display: none;"
     class="fixed inset-0 z-30 flex items-center justify-center overflow-auto" x-show="showTestModeModal">
    <div
        class="h-auto max-w-full rounded-lg pad-24 bg-white border border-gray-200 rounded-md shadow items-center popup-container ">
        <!-- Modal inner -->
        <div class="flex justify-right" style="float: right; clear: both;">
            <button type="button" class="z-50 cursor-pointer" @click="showTestModeModal = false,isCheckedTestMode = false, toggleOverflow(false),window.setTestMode(false)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
                     fill="none" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </button>
        </div>
        <div class="flex flex-row items-center justify-center">
            <div class="flex items-center justify-center">
                <img class="rotate-180 img-pop-align" src="<?= /* @noEscape */ $block->getImage("info.svg"); ?>" alt="After Processing Image" width="46"
                     height="46">
            </div>
        </div>
        <div class="flex flex-row items-center justify-center mt-6">
            <h3 class="text-base font-bold text-gray-900 optimize-page-head modal-heading">Enable Test mode?</h3>
        </div>
        <div class="flex flex-row items-center justify-center mt-6">
            <p class="text-l font-inter text-gray-500 text-lite-gray popup-text">
                When you enable Test mode, we disable all NitroPack’s optimizations and your site visitors are
                accessing your regular, unoptimized URLs.
            </p></div>
        <div class="flex flex-row items-center justify-center mt-10 items-center">
            <p class="p-4 bg-primary-50 text-test-model-700 rounded-lg my-6 antialiased font-normal font-inter popup-text"
               data-testid="paragraph">To view how a NitroPack optimized page will load and behave simply append <span
                    class="font-inter-bold font-bold">?testnitro=1</span> to any URL. (e.g.
                https://yourwebsite.com/?testnitro=1)</p>

        </div>
        <div class="flex flex-row items-center justify-center mt-6">
            <p class="text-l font-inter text-gray-500 text-lite-gray font-inter popup-text">
                This allows you to assess and fine-tune NitroPack’s performance  before implementing optimizations
                site-wide.
            </p>
        </div>

        <div class="flex flex-row items-center justify-center mt-10 items-center">
            <div class="flex items-center justify-center">
                <button  @click="showTestModeModal = false, isCheckedTestMode = false, window.setTestMode(false), toggleOverflow(false)" type="button"
                        class="bg-transparent text-purple-700 font-medium font-inter border border-purple-500 rounded cancel-btn">
                    Cancel
                </button>
            </div>
            <div class="flex items-center justify-center">
                <button type="button" id="safe_mode_active" @click="showTestModeModal = false,isCheckedTestMode = true,window.safeModeActive(),toggleOverflow(false)"
                        class="text-white font-medium font-inter border border-purple-500 rounded disconnectBtn">
                    Enable
                </button>
            </div>
        </div>
    </div>
</div>
