<?php

$nitroPackConfigHelper = $this->helper('NitroPack\NitroPack\Helper\NitroPackConfigHelper');
$nitroPackInvalidationHelper = $this->helper('NitroPack\NitroPack\Helper\InvalidationHelper');
$enabledMagentoCaches = $nitroPackConfigHelper->getDisabledCaches();
$settings = $block->getSettings();
$saveUrl = $block->getSaveUrl();
$varnishPurgeUrl = $block->getVarnishPurgeUrl();
$purgeUrl = $block->getCachePurgeUrl();
$warmupSaveUrl = $block->getCacheWarmupSaveUrl();
$warmupStartUrl = $block->getStartWarmupUrl();
$warmupConfig = $block->getWarmupConfig();
$warmupPauseUrl = $block->getPauseWarmupUrl();
$enableCachesUrl = $block->getEnableCachesUrl();
$safeModeEnableUrl = $block->getSafeModeEnableUrl();
$storeCurrencies = $block->getAvailableCurrencies();
$storeLocales = $block->getAvailableLocales();
$builtInPageRoutes = $block->getBuiltInPageTypeRoutes();
$builtInPageTypes = array_keys($builtInPageRoutes);

?>
<div id="tab_element">
    <ul class="tabs-horiz">
        <li>
            <a href="#tab1_content">
                <span>
                    <?php echo __("Dashboard"); ?>
                </span>
            </a>
        </li>
        <li>
            <a href="#tab2_content">
                <span>
                    <?php echo __("Diagnostics Report"); ?>
                </span>
            </a>
        </li>

    </ul>
</div>
<div id="tab_element_content">
    <div id="tab1_content">

        <div class="nitro">
            <?php

            if (!$nitroPackInvalidationHelper->checkInvalidationAndPurgeProcess() && !$nitroPackInvalidationHelper->checkCronJobIsSetup()) {

            } else {
                $cacheLabels = $block->getCacheLabels();
                if (!empty($enabledMagentoCaches) && !$nitroPackConfigHelper->getFullPageCacheValue()) {
                    ?>
                    <div class="row">
                        <div class="col mb-5">
                            <div class="message message-warning" id="system-config-caches-warning" role="warning">
                                <div class="alert-heading">The NitroPack extension is disabled! Incompatible Full Page
                                    Cache
                                    and
                                    Caching Application Setting:
                                </div>
                                <p class="alert-content">NitroPack requires to be set as <a
                                        href="<?= $block->getCacheManagementUrl() ?>">Caching Application</a> and <a
                                        href="<?= $block->getApplicationCacheUrl() ?>">Full Page Caching</a> enabled
                                </p>
                                <button id="enable-caches" class="btn btn-primary">Apply Fix Automatically</button>
                            </div>
                        </div>
                    </div>


                    <?php
                } else {
                    if (!empty($enabledMagentoCaches)) {
                        ?>
                        <div class="row">
                            <div class="col mb-5">
                                <div class="message message-warning" id="system-caches-warning" role="warning">
                                    <div class="alert-heading">The NitroPack extension is disabled! Incompatible Full
                                        Page
                                        Cache:
                                    </div>
                                    <p class="alert-content">NitroPack requires Full Page Caching enabled. Go to <a
                                            href="<?= $block->getCacheManagementUrl() ?>">Full Page Caching settings</a>
                                    </p>
                                    <button id="enable-caches" class="btn btn-primary">Apply Fix Automatically</button>
                                </div>
                            </div>
                        </div>
                        <?php
                    } else {

                        if (!$nitroPackConfigHelper->getFullPageCacheValue()) {
                            ?>
                            <div class="row">
                                <div class="col mb-5">
                                    <div class="message message-warning" id="config-caches-warning" role="warning">
                                        <div class="alert-heading">The NitroPack extension is disabled! Incompatible
                                            Caching
                                            application setting:
                                        </div>
                                        <p class="alert-content">NitroPack must be selected as a Cache Application. Go
                                            to <a
                                                href="<?= $block->getApplicationCacheUrl() ?>">Full Page Caching
                                                Application
                                                settings </a></p>
                                        <button id="enable-caches" class="btn btn-primary">Apply Fix Automatically
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                    }
                }
            } ?>

            <form id="nitro_settings">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <div class="card nitro-row">
                            <div class="iframe-container iframe-container-small">
                                <iframe scrolling="no"
                                        data-text-loading-invalidate-cache="text_loading_invalidate_cache"
                                        data-url-invalidate-cache="invalidate"
                                        data-text-loading-purge-cache="text_loading_purge_cache"
                                        data-url-purge-cache="<?= $saveUrl ?>" id="optimizations"
                                        data-src="<?= $block->getIntegrationUrl('optimizations') ?>"></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <div class="card nitro-row-one">

                            <div class="card-body" id="setting-widget">
                                <h5 class="card-title">General Settings</h5>
                                <div class="form-group row">

                                    <label class="col-md-10 col-form-label pl-0">
                                        Extension Status<br>
                                        <small class="text-secondary">Master ON/OFF switch for the extension.</small>
                                    </label>
                                    <div class="col-xs-2 text-right">
                                        <label class="switch">
                                            <input id="status" type="checkbox" name="enabled"<?php
                                            if (!empty($enabledMagentoCaches) || !$nitroPackConfigHelper->getFullPageCacheValue()) {
                                                echo "disabled";
                                            } ?>
                                                   value="<?= ($settings->enabled ? 1 : 0) ?>" <?= ($settings->enabled ? 'checked' : '') ?>>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                                <?php
                                if (!empty($enabledMagentoCaches) || !$nitroPackConfigHelper->getFullPageCacheValue()) { ?>
                                    <div class="form-group row" id="enabledMagentoCachesWarning">
                                        <div class="messages">
                                            <div class="message message-warning warning">
                                                <div class="general-message" data-ui-id="messages-message-warning">
                                                    NitroPack is disabled due to incompatible Caching setting
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php
                                } ?>
                                <div class="form-group row">
                                    <label class="col-md-10 col-form-label pl-0">
                                        Cache Warmup<br>
                                        <small class="text-secondary">Automatically re-optimizes purged/invalidated
                                            pages.</small>
                                    </label>
                                    <div class="col-xs-2 text-right">

                                        <label class="switch">
                                            <input id="cache_warmup" type="checkbox"
                                                   name="cacheWarmup" <?= ($settings->cacheWarmup ? 'checked' : '') ?>/>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-10 col-form-label pl-0">Enhanced Caching With Caching Variation<br>
                                        <small class="text-secondary">Cache different versions of a page based on customer group, selected store, currency, language, and customer logged in or not .</small>
                                    </label>
                                    <div class="col-xs-2 text-right">
                                        <label class="switch">
                                            <input id="cache_to_customer_login" type="checkbox"
                                                   name="cache_to_login_customer" <?= (isset($settings->cache_to_login_customer) && $settings->cache_to_login_customer ? 'checked' : '') ?>/>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-10 col-form-label pl-0">
                                        Test Mode<br>
                                        <small class="text-secondary">Learn more about this feature
                                            <a href="https://support.nitropack.io/hc/en-us/articles/360060910574-Safe-Mode"
                                               target="_blank" rel="noreferrer noopener">here</a>
                                        </small>
                                    </label>
                                    <div class="col-xs-2 text-right">
                                        <label class="switch">
                                            <input id="safe_mode" type="checkbox"
                                                   name="safeMode" <?= (isset($settings->safeMode) && $settings->safeMode ? 'checked' : '') ?>/>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                                <?php if (isset($_SERVER['HTTP_ACCEPT_ENCODING']) && strpos($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') !== false) {


                                   $getHeader = get_headers($block->getStoreUrls(), true);

                                    if(isset($getHeader['Content-Encoding']) && $getHeader['Content-Encoding'] != 'gzip'){

                                    ?>
                                <div class="form-group row">
                                    <label class="col-md-10 col-form-label pl-0">
                                        GZIP Compression<br>
                                        <small class="text-secondary">ON/OFF switch for HTML compression by NitroPack</small>
                                    </label>
                                    <div class="col-xs-2 text-right">
                                        <label class="switch">
                                            <input id="gzip_mode" type="checkbox"
                                                   name="gzip" <?= (isset($settings->gzip) && $settings->gzip ? 'checked' : '') ?>/>
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </div>
                                <?php }} ?>
                                <div class="form-group row" style="margin-bottom: 0; clear: both;">

                                    <small class="text-secondary" style="width: 100%;clear: both;">
                                        <span style="width: 70%; float: left; padding-top: 1em">Adjust Optimization Settings at your NitroPack Dashboard</span>
                                        <span style="width: 30%; float: right;"><a target="_blank"
                                                                                   href="https://nitropack.io/user/login"
                                                                                   class="btn btn-primary btn-sm ml-3"
                                                                                   style="font-size: 13px; padding: 6px; width: 100%; float: right; ">
                                    <svg width="30" height="18" viewBox="0 0 35 18" fill="none"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M17.5031 2.96727C25.5536 2.96727 32.0828 9.60919 32.0828 17.8099H35C35 7.97532 27.1624 0 17.5031 0C7.84386 0 0 7.97532 0 17.8099H2.91719C2.91719 9.61545 9.44643 2.96727 17.5031 2.96727Z"
                                            fill="#25F5CE"/>
                                        <path
                                            d="M14.7989 16.4698C14.1729 15.1051 14.9742 13.5025 16.4265 13.2146L26.6868 10.8232L18.2983 17.2899C17.1465 18.2414 15.4249 17.8408 14.7989 16.4698Z"
                                            fill="#25F5CE"/>
                                    </svg>
                                    Dashboard</a><span></small>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="col-md-4">
                        <div class="card nitro-plan">
                            <div class="iframe-container iframe-container-small">
                                <iframe scrolling="no" id="plan"
                                        data-src="<?= $block->getIntegrationUrl('plan') ?>"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-5">
                        <div class="card">
                            <div class="iframe-container iframe-container-small">
                                <iframe scrolling="no" id="quicksetup"
                                        data-src="<?= $block->getIntegrationUrl('quicksetup') ?>"></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Service Status</h5>
                                <div class="form-group mb-4">
                                    <p class="col-form-label">API Key</p>
                                    <div>
                                        <p id="site-id"><?= $settings->siteId; ?></p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <p class="col-form-label">Site</p>
                                    <div>
                                        <p id="site"><?= $block->getStoreUrls(); ?></p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <p>Cache Warmup Status</p>
                                    <?php
                                    if ($settings->cacheWarmup): ?>
                                        <p><small><span class="warmup-stats"><i
                                                        class="fa fa-circle text-success"></i> Enabled</span></small>
                                        </p>
                                    <?php
                                    else: ?>
                                        <p><small><span class="warmup-stats"><i
                                                        class="fa fa-circle text-danger"></i> Disabled</span></small>
                                        </p>
                                    <?php
                                    endif; ?>
                                </div>
                            </div>
                            <div class="card-footer">
                                <small class="pull-left">
							<span data-connection="connected" class="text-secondary" style="display: inline;">
								<i class="fa fa-circle text-success"></i> Extension Active
							</span>
                                    <span data-connection="disabled" class="text-secondary" style="display: none;">
								<i class="fa fa-circle text-danger"></i> Extension Disabled
							</span>
                                </small>
                                <small class="pull-right">
                                    <a href="javascript:void(0);" id="disconnect" data-loading-text="Disconnecting..."
                                       class="card-link text-secondary">
                                        <i class="fa fa-power-off"></i> Disconnect
                                    </a>
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-5">


                        <div class="card">
                            <div class="iframe-container iframe-container-medium">
                                <iframe scrolling="no" id="beforeafter"
                                        data-src="<?= $block->getIntegrationUrl('beforeafter') ?>"></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Product Attributes Cache Behavior</h5>
                            <p><small>This section shows whether the cache will be purged when a product attribute is
                                    updated.</small></p>
                            <br>
                            <div class="form-group row"
                                 style="border-bottom: solid 1px #ddd;  height: 25px;">
                                <div class="col-md-6"><h6><strong>Attribute</strong></h6></div>
                                <div class="col-md-6"><h6><strong>Purge Nitro Cache</strong></h6></div>
                                <div class="clearfix"></div>
                            </div>

                            <?php foreach ($block->getNitroPackAttribute()['items'] as $value): ?>
                                <div class="form-group row"
                                     style="border-bottom: solid 1px #ddd;  height: 25px;">
                                    <div class="col-md-6"><p><?= $value['frontend_label']; ?></p></div>
                                    <div class="col-md-6"><p><?= $value['nitro_purge'] == 1 ? 'Yes' : 'No'; ?></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            <?php endforeach; ?>
                            <div class="form-group row">
                                <div class="col-md-8"></div>
                                <div class="col-md-4">
                                    <a  href="<?= $block->getProductAttributeUrl(); ?>" class="btn btn-primary btn-sm ml-3" style="font-size: 13px; padding: 6px; width: 100%; float: right; ">
                                        Manage All Attributes</a>
                                </div>

                            </div>
                        </div>

                    </div>

                </div>

                </div>
            </form>
            <script id="template-nitropack-notification-success" type="text/template">
                <div id="nitropack-notification" class="nitro" data-type="success">
                    <div class="alert alert-success" id="nitropack-notification-message">{message}</div>
                </div>
            </script>
            <script id="template-nitropack-notification-danger" type="text/template">
                <div id="nitropack-notification" class="nitro" data-type="danger">
                    <div class="alert alert-danger" id="nitropack-notification-message">{message}</div>
                </div>
            </script>
            <script id="template-nitropack-notification-warning" type="text/template">
                <div id="nitropack-notification" class="nitro" data-type="warning">
                    <div class="alert alert-warning" id="nitropack-notification-message">{message}</div>
                </div>
            </script>
            <script id="template-nitropack-notification-info" type="text/template">
                <div id="nitropack-notification" class="nitro" data-type="info">
                    <div class="alert alert-info" id="nitropack-notification-message">{message}</div>
                </div>
            </script>


        </div>
        <div id="cacheWarmupTemplates" style="display: none">
            <div id="cacheWarmupModal">
                <div class="modal-body">
                    <div class="form-group">
                        <h5 class="modal-heading mb-2">Store Views</h5>
                        {%STORE_VIEWS%}
                        <hr>
                        <h5 class="modal-heading mb-2">Currencies</h5>
                        <div class="cacheWarmupCurrencyContainer">
                            {%CURRENCIES%}
                        </div>
                        <hr>
                        <h5 class="modal-heading mb-2">Pages</h5>
                        {%PAGE_TYPES%}
                    </div>
                </div>
            </div>
            <div id="cacheWarmupStoreView">
                <div class="row mb-3">
                    <div class="col-xs-8 col-form-label">
                        {%STORE_NAME%}
                        {%STORE_CODE%}
                    </div>
                    <div class="col-xs-4 text-right">
                        {%STORE_SWITCH%}
                    </div>
                </div>
            </div>
            <div id="cacheWarmupCurrency">
                <div class="row mb-3">
                    <div class="col-xs-8 col-form-label">
                        {%CURRENCY_LABEL%}
                        {%STORE_CODES%}
                    </div>
                    <div class="col-xs-4 text-right">
                        {%CURRENCY_SWITCH%}
                    </div>
                </div>
            </div>
            <div id="cacheWarmupEmptyCurrencies">
                <div class="row mb-3">
                    <div class="col-xs-8 col-form-label">
                        Enable the warmup for at least one store view to select currencies.
                    </div>
                    <div class="col-xs-4 text-right">
                        <!-- no switch -->
                    </div>
                </div>
            </div>
            <div id="cacheWarmupPageType">
                <div class="row mb-2">
                    <div class="col-xs-8 col-form-label">{%PAGE_LABEL%}</div>
                    <div class="col-xs-4 text-right">
                        {%PAGE_SWITCH%}
                    </div>
                </div>
            </div>
            <div id="cacheWarmupStoreCodeBadge">
                <span class="badge" customstyle="">{%STORE_CODE%}</span>
            </div>
            <div id="cacheWarmupSwitch">
                <label class="switch">
                    <input type="checkbox" class="cacheWarmupSwitch" value="1" customattributes="">
                    <span class="slider round" data-toggle="tooltip" title="{%SWITCH_TITLE%}"></span>
                </label>
            </div>
        </div>
    </div>
    <div id="tab2_content">
        <?php echo $this->getChildHtml('DiagnosticsBlock'); ?>
    </div>
</div>

<script type="text/javascript">
    require(["jquery", "mage/backend/tabs"], function ($) {
        $(function () {
            $('#tab_element').tabs({
                active: 'tab1_content',  // active tab elemtn id
                destination: '#tab_element_content', // tab content destination element id
                shadowTabs: []
            });
        });
    });
    require(['jquery', 'Magento_Ui/js/modal/alert', 'NitroPack_NitroPack/js/overlay'], function ($, magentoAlert, cardOverlay) {
        $(document).ready(function () {

            if ($('.nitro-row-one').height() >= $('.nitro-plan').height()) {
                $('.nitro-plan').css('height', $('.nitro-row-one').height());
                $('.nitro-row').css('height', $('.nitro-row-one').height());
            }
            let currentStoreCode = <?= json_encode($block->getStoreGroup()->getCode()) ?>;
            let builtInPageTypes = <?= json_encode($builtInPageTypes) ?>;

            $('iframe[data-src]').each((index, iframe) => {
                $(iframe).attr('src', $(iframe).attr('data-src'));
            });

            let extensionStatus = $('input[name=enabled]').val();
            if (extensionStatus == 1) {
                $('span[data-connection="connected"]').show();
                $('span[data-connection="disabled"]').hide();
            } else {
                $('span[data-connection="connected"]').hide();
                $('span[data-connection="disabled"]').show();
            }

            $(document).on('change', '#nitro_settings input[type=checkbox]', function () {
                let value = $(this).is(':checked') ? 1 : 0;
                let setting = $(this).attr('name');

                let data = {};
                data[setting] = value;
                let saveRequest = true;

                switch (setting) {
                    case 'cacheWarmup':
                        updateCacheWarmupStatus(!!value);

                        break;
                    case 'enabled':
                        if (data[setting] == 1) {
                            $('input[name=enabled]').val(1);
                            $('span[data-connection="connected"]').show();
                            $('span[data-connection="disabled"]').hide();
                        } else {
                            $('input[name=enabled]').val(0);
                            $('span[data-connection="connected"]').hide();
                            $('span[data-connection="disabled"]').show();
                        }
                        break;
                    case 'safeMode':
                        saveRequest = false;
                        break;
                    case 'custom_route_status':
                        saveRequest = false;
                        saveCustomRoutes();
                        break;
                }

                if (saveRequest) {
                    $.ajax({
                        url: '<?= $saveUrl ?>',
                        method: 'POST',
                        dataType: 'json',
                        data: data,
                        success: function (response) {
                            if (response.saved) {
                                Notification.success('Saved successfully');
                                if (<?= $block->checkVarnishEnable()?>) {
                                    $.get('<?=  $block->getVarnishPurgeUrl() ?>', function (data) {
                                    });
                                }
                            } else {
                                Notification.danger('Something went wrong');
                            }
                        }
                    })
                }
            });
            var toggleActiveStoreCacheWarmup = (newState) => {
                $('#cache_warmup').prop('checked', newState);
                updateCacheWarmupStatus(newState);
            };

            var updateCacheWarmupStatus = (newState) => {
                if (newState) {
                    $('.warmup-stats').html('<small><span class="warmup-stats"><i class="fa fa-circle text-success"></i> Enabled</span></small>');
                } else {
                    $('.warmup-stats').html('<small><span class="warmup-stats"><i class="fa fa-circle text-danger"></i> Disabled</span></small>');
                }
            }

            $('#cache_warmup').change(function () {
                let warmupEnabled = $(this).is(':checked');
                setCacheWarmupTypes(warmupEnabled);
                setRunWarmupButtonStatus(warmupEnabled);
            });

            $('#disconnect').on('click', function (event) {
                event.preventDefault();
                $(this).html($(this).attr('data-loading-text'));
                //debugger;
                if (confirm('NitroPack will be disconnected. Are you sure?')) {
                    $.ajax({
                        url: '<?= $block->getDisconnectUrl() ?>',
                        method: 'GET',
                        success: function (response) {
                            if (response.disconnected == true) {
                                if (<?= $block->checkVarnishEnable()?>) {
                                    $.get('<?=  $block->getVarnishPurgeUrl() ?>', function (data) {
                                        window.location = '<?= $block->getConnectUrl() ?>';

                                    });
                                } else {
                                    window.location = '<?= $block->getConnectUrl() ?>';
                                }
                            }
                        }
                    });
                } else {
                    $(this).html('<a href="javascript:void(0);" id="disconnect" data-loading-text="Disconnecting..." class="card-link text-secondary"> <i class="fa fa-power-off"></i> Disconnect </a>');
                }
            });

            $('#start-warmup').click(function (event) {
                event.preventDefault();
                $.ajax({
                    url: '<?= $warmupStartUrl ?>',
                    method: 'POST',
                    dataType: 'json',
                    data: {run: 1},
                    success: function (response) {
                        // @TODO proper response handling
                        if (response.success) {
                            console.log('Successfully started warmup', response);
                            $('#start-warmup').css('display', 'none').attr('disabled', true);
                            $('#pause-warmup').css('display', 'block').attr('disabled', false);
                        } else {
                            console.log('[Un]Successfully did not start warmup', response);
                        }
                    }
                });
            });

            $('#pause-warmup').click(function (event) {
                event.preventDefault();
                $.ajax({
                    url: '<?= $warmupPauseUrl ?>',
                    method: 'POST',
                    dataType: 'json',
                    data: {run: 1},
                    success: function (response) {
                        // @TODO proper response handling
                        if (response.paused) {
                            $('#pause-warmup').css('display', 'none').attr('disabled', true);
                            $('#start-warmup').css('display', 'block').attr('disabled', false);
                        } else {
                            console.log('Pause failed', response);
                        }
                    }
                });
            });

            $('#enable-caches').click(function (event) {
                event.preventDefault();
                $.ajax({
                    url: '<?= $enableCachesUrl ?>',
                    method: 'POST',
                    dataType: 'json',
                    data: {run: 1},
                    success: function (response) {
                        // @TODO proper response handling
                        if (response.enabled) { // we expect disabled to be true if we have successfully disabled the system caches
                            <?php if (!empty($enabledMagentoCaches) && !$nitroPackConfigHelper->getFullPageCacheValue()) { ?>
                            Notification.success('Successfully Enabled system caches and The Caching application successfully set to NitroPack');
                            <?php }else {if (!empty($enabledMagentoCaches) ){?>
                            Notification.success('Successfully Enabled system caches ');
                            <?php }else {if (!$nitroPackConfigHelper->getFullPageCacheValue() ){ ?>
                            Notification.success('The Caching application successfully set to NitroPack');
                            <?php }}} ?>
                            $('#system-caches-warning').remove();
                            $('#config-caches-warning').remove();
                            $('#system-config-caches-warning').remove();
                            $('#status').removeAttr('disabled');
                            $('#enabledMagentoCachesWarning').remove();
                            if (response.extension_enabled) {
                                if ($('#status').val() == 0) {
                                    $('#status').click();
                                    $('#status').val(1);
                                }
                            }
                            $('#system_messages').remove();
                            $('.nitro-row-one').css('height', $('.nitro-plan').height());
                        } else {
                            Notification.danger('Failed disabling the system caches');
                        }
                    }
                });
            })
            $("#safe_mode").on("click", function (e) {
                let isEnabled = $(this).is(":checked");
                if (isEnabled) {
                    enableSafemode();
                } else {
                    $('#test-mode-disable').hide();
                    let confirmHtml = '<p><strong>Purge Cache?</strong></p>' +
                        '<p>It is recommended to perform a full cache purge so all changes are correctly applied.</p>' +
                        '<p>Would you like to purge the cache now?</p>' +
                        '<p><a href="javascript:void(0);" onclick="closeModalOverlay()" class="btn btn-default btn-sm">No</a>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="performCachePurge()" class="btn btn-info btn-sm">Yes (Recommended)</a></p>';
                    $("#setting-widget").cardOverlay("notify", {message: confirmHtml, dismissable: false});
                    disableSafeMode();
                }
            });



            function setCacheWarmupTypes(enabled) {
                $('[name^="warmupTypes-"]').attr('disabled', !enabled);
            }

            function setRunWarmupButtonStatus(enabled) {
                if (enabled) {
                    $('#start-warmup').attr('disabled', false);
                    $('#start-warmup').css('display', 'block');
                    $('#pause-warmup').css('display', 'none');
                } else {
                    $('#start-warmup').attr('disabled', true);
                    $('#start-warmup').css('display', 'none');
                    $('#pause-warmup').css('display', 'none');
                }
            }

            function pushAlertNotification(msg, status) {
                $('#container > .nitro').prepend('<div class="row"><div class="col"><div class="alert alert-' + status + ' alert-dismissible fade show" role="alert">' + msg + '<button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span> </button></div></div></div>');
            }


            NitroPack.Optimizations.setPurgeCacheHandler(async function (success, error) {
                if ($('#status').val() == 1) {
                    purgeCache().then(function () {
                        success();
                    }, function () {
                        error();
                    });
                } else {
                    Notification.danger("NitroPack is disabled. The Cache Purge option is not possible");
                }
            });

        });
        var safeModeUrl = "<?= $safeModeEnableUrl; ?>";

        var enableSafemode = () => {
            $.post(safeModeUrl, {
                action: 'nitropack_enable_safemode'
            }, function (response) {
                var resp = JSON.parse(response);
                if (resp.type == "success") {
                    Notification.success('Success! Safe mode has been enabled successfully!');
                    // Success notification
                } else {
                    Notification.error('Error! There was an error while enabling safe mode!');
                }
            });
        }

        var disableSafeMode = () => {
            $.post(safeModeUrl, {
                action: 'nitropack_disable_safemode'
            }, function (response) {
                var resp = JSON.parse(response);
                if (resp.type == "success") {
                    // Success notification
                    Notification.success('Success! Safe mode has been disabled successfully!');
                } else {
                    // Error notification
                    Notification.error('Error! There was an error while enabling safe mode!');
                }
            });
        }




        window.closeModalOverlay = function () {
            $("#setting-widget").cardOverlay("clear");
        }

        function purgeCache() {
            let data = {'cache.purge': 1};
            return $.ajax({
                url: '<?= $purgeUrl ?>',
                method: 'POST',
                dataType: 'json',
                data: data,
                success: function (response) {
                    if (response.purged) {
                        Notification.success(response.message);
                    } else {
                        Notification.danger(response.message);
                    }
                },
                error: function (response, errType, msg) {
                    Notification.danger('Cache was not purged. Error type: ' + errType + '. Error message: ' + msg);
                }
            });
        }

        window.performCachePurge = () => {
            purgeCache();
            closeModalOverlay();
        }

    });
</script>
