<div class="nitro support-bg" style=" background-image: url('<?php echo $this->getViewFileUrl('NitroPack_NitroPack::img/support-bg.jpg');?>');" >
    <div class="row justify-content-center">
        <div class="col-md-12 col-sm-12 col-lg-5">
            <div class="card support-card">
                <div class="text-center p-3">
                    <div class="support-card-img">
                        <img src="<?php echo $this->getViewFileUrl('NitroPack_NitroPack::img/404-image.png');?>" width="400" id="support-logo" alt="NitroPack.io">
                    </div>
                    <div class="support-h2">
                        Oh No!
                    </div>
                    <br>
                    <div class="support-p1">
                    Look like we are experiencing some technical issues (Sorry about that)
                    </div>
                    <div class="support-p1">
                        Please try again or <a href="https://support.nitropack.io/">ask for a support</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
