<?php
$nitroPackConfigHelper = $this->helper('NitroPack\NitroPack\Helper\AdminFrontendUrl');
$settingPage = $this->getUrl('NitroPack/Settings/Index');
?>
<div class="row justify-content-center ">
    <div class="container-sm h-[600px]"">
        <div class="flex justify-between items-center">
            <img class="mx-auto mt-[80px] mb-[80px]"
                 src="<?php echo $this->getViewFileUrl('NitroPack_NitroPack::img/warning.png'); ?>" id="support-logo"
                 alt="NitroPack.io">
        </div>
        <div class="text-grey-700 text-center font-inter text-24-32 font-bold">
            We could not load the page due to a technical issue.
        </div>
        <br>
        <div class="text-grey-700 text-center font-inter text-18-27 mb-14">
            Our technical team is already aware of the issue and is working to resolve it.<br> We apologize for the
            inconvenience and appreciate your patience. <br>If the problem persists, please contact our <a class="text-blue" target="_blank" href="https://support.nitropack.io/en/ ">support team.</a>
        </div>
        <div class="flexitems-center">
        <button onClick="window.location.href='<?= $settingPage ?>'" class="mx-auto flex gap-2 justify-center items-center border-solid border border-purple font-inter rounded-lg hover:bg-purple-100 text-purple font-medium font-inter hover:text-purple py-[8px] px-[20px] stroke-purple">
            Refresh now</button>
        </div>
    </div>
</div>
